server:
  port: ${blog.port}

  servlet:
    context-path: /api


spring:
  datasource:
    username: ${blog.mysql.username}
    password: ${blog.mysql.password}
    url: jdbc:mysql://${host}:3306/blog2?&characterEncoding=utf-8&userSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${host}
    port: 6379
    password:

  profiles:
    active: dev


logging:
  level:
    com.Aaron: debug